pluginManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'Loom'; url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'Ladysnake'; url = 'https://maven.ladysnake.org/releases' }
        maven { name = 'GeckoLib'; url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
        maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' }
        maven { name = 'KosmX'; url = 'https://maven.kosmx.dev/' }
        maven { name = 'Jitpack'; url = 'https://jitpack.io' }
        mavenCentral()
    }
}