# setup_progression_complete.ps1
# Master script: ALL remaining Progression module files
# Mini-games, UI, KeyBindings, Packets, Data, README
# ASCII-only, UTF-8 NoBOM, idempotent

$ErrorActionPreference = "Stop"

Write-Host "[INFO] Starting COMPLETE Progression module setup..." -ForegroundColor Cyan

$baseJava = "src/main/java/com/example/shinobicore/modules/progression"
$baseData = "src/main/resources/data/shinobicore/progression"
$baseAssets = "src/main/resources/assets/shinobicore/progression"

# 1. Directories
$dirs = @(
    "$baseJava/minigame",
    "$baseJava/client",
    "$baseJava/ui",
    "$baseJava/ui/widgets",
    "$baseJava/network",
    "$baseJava/service",
    "$baseJava/data",
    "$baseJava/event",
    "$baseJava/component",
    "$baseJava/view",
    "$baseJava/commands",
    "$baseJava/config",
    "$baseData/minigames",
    "$baseData/tree",
    "$baseData/attunement",
    "$baseData/balance",
    "$baseAssets/textures"
)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        Write-Host "[OK] Created directory: $dir" -ForegroundColor Green
    }
}

# 2. UTF-8 NoBOM writer
function Write-Utf8NoBom {
    param([string]$Path, [string[]]$Lines)
    $content = $Lines -join "`r`n"
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    $fullPath = Join-Path (Get-Location) $Path
    [System.IO.File]::WriteAllText($fullPath, $content, $utf8NoBom)
    Write-Host "[OK] Written: $Path" -ForegroundColor Green
}

# ==========================================
# SECTION A: MINI-GAME DATA
# ==========================================

Write-Utf8NoBom -Path "$baseJava/data/MiniGameDefinition.java" -Lines @(
    'package com.example.shinobicore.modules.progression.data;'
    ''
    'import java.util.Map;'
    ''
    'public record MiniGameDefinition('
    '    String id,'
    '    String type,'
    '    Map<String, Float> params,'
    '    int rewardXp,'
    '    String rewardStat,'
    '    String rewardElement'
    ') {}'
)

Write-Utf8NoBom -Path "$baseJava/data/MiniGameRegistry.java" -Lines @(
    'package com.example.shinobicore.modules.progression.data;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    'import java.util.Collection;'
    'import java.util.HashMap;'
    'import java.util.Map;'
    'import java.util.Optional;'
    ''
    'public final class MiniGameRegistry {'
    '    private static final Map<String, MiniGameDefinition> GAMES = new HashMap<>();'
    ''
    '    private MiniGameRegistry() {}'
    ''
    '    public static void register(MiniGameDefinition def) {'
    '        if (def == null || def.id() == null) return;'
    '        if (GAMES.containsKey(def.id())) {'
    '            ShinobiLogger.error("progression", "Duplicate minigame ID: " + def.id(), null);'
    '            return;'
    '        }'
    '        GAMES.put(def.id(), def);'
    '    }'
    ''
    '    public static Optional<MiniGameDefinition> get(String id) {'
    '        return Optional.ofNullable(GAMES.get(id));'
    '    }'
    ''
    '    public static Collection<MiniGameDefinition> getAll() {'
    '        return GAMES.values();'
    '    }'
    ''
    '    public static void clear() { GAMES.clear(); }'
    ''
    '    public static int size() { return GAMES.size(); }'
    '}'
)

# ==========================================
# SECTION B: MINI-GAME RESULT PACKET
# ==========================================

Write-Utf8NoBom -Path "$baseJava/network/MiniGameResultPacket.java" -Lines @(
    'package com.example.shinobicore.modules.progression.network;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    'import com.example.shinobicore.modules.progression.service.XpSourceService;'
    'import io.netty.buffer.Unpooled;'
    'import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;'
    'import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;'
    'import net.minecraft.network.PacketByteBuf;'
    'import net.minecraft.server.network.ServerPlayerEntity;'
    'import net.minecraft.util.Identifier;'
    ''
    'public final class MiniGameResultPacket {'
    '    public static final Identifier ID ='
    '        new Identifier("shinobicore", "progression_minigame_result");'
    ''
    '    private MiniGameResultPacket() {}'
    ''
    '    public static void sendToServer(String gameId, boolean success) {'
    '        PacketByteBuf buf = new PacketByteBuf(Unpooled.buffer());'
    '        buf.writeString(gameId);'
    '        buf.writeBoolean(success);'
    '        ClientPlayNetworking.send(ID, buf);'
    '    }'
    ''
    '    public static void registerServer() {'
    '        ServerPlayNetworking.registerGlobalReceiver(ID, (server, player, handler, buf, sender) -> {'
    '            final String gameId = buf.readString();'
    '            final boolean success = buf.readBoolean();'
    ''
    '            server.execute(() -> handle(player, gameId, success));'
    '        });'
    '        ShinobiLogger.module("progression", "Registered C2S packet: " + ID);'
    '    }'
    ''
    '    private static void handle(ServerPlayerEntity player, String gameId, boolean success) {'
    '        if (player == null || gameId == null) return;'
    '        if (!success) return;'
    ''
    '        com.example.shinobicore.modules.progression.data.MiniGameRegistry.get(gameId).ifPresent(def -> {'
    '            int xp = def.rewardXp();'
    '            if (xp > 0) {'
    '                XpSourceService.awardXp(player, xp, "minigame:" + gameId);'
    '            }'
    '            ShinobiLogger.module("progression",'
    '                player.getName().getString() + " completed minigame: " + gameId);'
    '        });'
    '    }'
    '}'
)

# ==========================================
# SECTION C: PROGRESSION PACKETS REGISTRY
# ==========================================

Write-Utf8NoBom -Path "$baseJava/network/ProgressionPackets.java" -Lines @(
    'package com.example.shinobicore.modules.progression.network;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    ''
    'public final class ProgressionPackets {'
    '    private ProgressionPackets() {}'
    ''
    '    public static void registerServer() {'
    '        ProgressionActionPacket.registerServer();'
    '        AttunementAttemptPacket.registerServer();'
    '        MiniGameResultPacket.registerServer();'
    '        ShinobiLogger.module("progression", "All server packets registered");'
    '    }'
    ''
    '    public static void registerClient() {'
    '        ProgressionStateSyncPacket.registerClient();'
    '        LevelUpPacket.registerClient();'
    '        StatChangedPacket.registerClient();'
    '        ShinobiLogger.module("progression", "All client packets registered");'
    '    }'
    '}'
)

# ==========================================
# SECTION D: LEVEL UP + STAT CHANGED PACKETS
# ==========================================

Write-Utf8NoBom -Path "$baseJava/network/LevelUpPacket.java" -Lines @(
    'package com.example.shinobicore.modules.progression.network;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    'import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;'
    'import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;'
    'import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;'
    'import net.minecraft.network.PacketByteBuf;'
    'import net.minecraft.server.network.ServerPlayerEntity;'
    'import net.minecraft.util.Identifier;'
    ''
    'public final class LevelUpPacket {'
    '    public static final Identifier ID ='
    '        new Identifier("shinobicore", "progression_level_up");'
    ''
    '    private LevelUpPacket() {}'
    ''
    '    public static void sendTo(ServerPlayerEntity player, int newLevel) {'
    '        PacketByteBuf buf = PacketByteBufs.create();'
    '        buf.writeInt(newLevel);'
    '        ServerPlayNetworking.send(player, ID, buf);'
    '    }'
    ''
    '    public static void registerClient() {'
    '        ClientPlayNetworking.registerGlobalReceiver(ID, (client, handler, buf, sender) -> {'
    '            final int newLevel = buf.readInt();'
    ''
    '            client.execute(() -> {'
    '                // Client can play level-up animation/sound here'
    '                ShinobiLogger.module("progression",'
    '                    "Client received level-up: " + newLevel);'
    '            });'
    '        });'
    '        ShinobiLogger.module("progression", "Registered S2C packet: " + ID);'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/network/StatChangedPacket.java" -Lines @(
    'package com.example.shinobicore.modules.progression.network;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    'import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;'
    'import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;'
    'import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;'
    'import net.minecraft.network.PacketByteBuf;'
    'import net.minecraft.server.network.ServerPlayerEntity;'
    'import net.minecraft.util.Identifier;'
    ''
    'public final class StatChangedPacket {'
    '    public static final Identifier ID ='
    '        new Identifier("shinobicore", "progression_stat_changed");'
    ''
    '    private StatChangedPacket() {}'
    ''
    '    public static void sendTo(ServerPlayerEntity player, String statId, int newLevel) {'
    '        PacketByteBuf buf = PacketByteBufs.create();'
    '        buf.writeString(statId);'
    '        buf.writeInt(newLevel);'
    '        ServerPlayNetworking.send(player, ID, buf);'
    '    }'
    ''
    '    public static void registerClient() {'
    '        ClientPlayNetworking.registerGlobalReceiver(ID, (client, handler, buf, sender) -> {'
    '            final String statId = buf.readString();'
    '            final int newLevel = buf.readInt();'
    ''
    '            client.execute(() -> {'
    '                // Client can play stat-change animation here'
    '                ShinobiLogger.module("progression",'
    '                    "Client received stat change: " + statId + " -> " + newLevel);'
    '            });'
    '        });'
    '        ShinobiLogger.module("progression", "Registered S2C packet: " + ID);'
    '    }'
    '}'
)

# ==========================================
# SECTION E: TRAINING MINI-GAMES (Client)
# ==========================================

Write-Utf8NoBom -Path "$baseJava/minigame/TimingMiniGame.java" -Lines @(
    'package com.example.shinobicore.modules.progression.minigame;'
    ''
    'import com.example.shinobicore.modules.progression.network.MiniGameResultPacket;'
    'import net.minecraft.client.gui.DrawContext;'
    ''
    'public final class TimingMiniGame extends MiniGameScreen {'
    '    private float markerPos = 0.0f;'
    '    private float targetStart = 0.4f;'
    '    private float targetEnd = 0.6f;'
    '    private float speed = 1.5f;'
    '    private boolean movingRight = true;'
    '    private int resultTicks = 0;'
    ''
    '    public TimingMiniGame(String gameId, float speed,'
    '            float targetStart, float targetEnd) {'
    '        super("Timing: " + gameId, gameId);'
    '        this.speed = speed;'
    '        this.targetStart = targetStart;'
    '        this.targetEnd = targetEnd;'
    '    }'
    ''
    '    @Override'
    '    protected void gameTick() {'
    '        if (movingRight) {'
    '            markerPos += speed / 20.0f;'
    '            if (markerPos >= 1.0f) movingRight = false;'
    '        } else {'
    '            markerPos -= speed / 20.0f;'
    '            if (markerPos <= 0.0f) {'
    '                state = State.FAILURE;'
    '                MiniGameResultPacket.sendToServer(gameId, false);'
    '            }'
    '        }'
    ''
    '        if (state != State.PLAYING) {'
    '            resultTicks++;'
    '            if (resultTicks > 40) close();'
    '        }'
    '    }'
    ''
    '    @Override'
    '    public boolean mouseClicked(double mouseX, double mouseY, int button) {'
    '        if (state != State.PLAYING) return false;'
    ''
    '        boolean inZone = markerPos >= targetStart && markerPos <= targetEnd;'
    '        state = inZone ? State.SUCCESS : State.FAILURE;'
    '        MiniGameResultPacket.sendToServer(gameId, inZone);'
    '        return true;'
    '    }'
    ''
    '    @Override'
    '    protected void gameRender(DrawContext ctx, int mouseX, int mouseY, float delta) {'
    '        int barWidth = 200;'
    '        int barHeight = 20;'
    '        int barX = (width - barWidth) / 2;'
    '        int barY = height / 2;'
    ''
    '        // Background bar'
    '        ctx.fill(barX, barY, barX + barWidth, barY + barHeight, 0xFF333333);'
    ''
    '        // Target zone'
    '        int zoneStart = barX + (int)(barWidth * targetStart);'
    '        int zoneEnd = barX + (int)(barWidth * targetEnd);'
    '        ctx.fill(zoneStart, barY, zoneEnd, barY + barHeight, 0x8800FF00);'
    ''
    '        // Marker'
    '        int markerX = barX + (int)(barWidth * markerPos);'
    '        ctx.fill(markerX - 2, barY - 5, markerX + 2, barY + barHeight + 5, 0xFFFFFFFF);'
    ''
    '        // Status'
    '        String statusText = switch (state) {'
    '            case PLAYING -> "Click when the marker is in the green zone";'
    '            case SUCCESS -> "Perfect timing!";'
    '            case FAILURE -> "Missed! Try again.";'
    '        };'
    '        ctx.drawCenteredTextWithShadow(textRenderer, statusText, width / 2, barY + 40, 0xFFFFFF);'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/minigame/TargetMiniGame.java" -Lines @(
    'package com.example.shinobicore.modules.progression.minigame;'
    ''
    'import com.example.shinobicore.modules.progression.network.MiniGameResultPacket;'
    'import net.minecraft.client.gui.DrawContext;'
    ''
    'import java.util.ArrayList;'
    'import java.util.List;'
    ''
    'public final class TargetMiniGame extends MiniGameScreen {'
    '    private static final int TARGET_COUNT = 5;'
    '    private static final int TARGET_RADIUS = 15;'
    '    private final List<int[]> targets = new ArrayList<>();'
    '    private int hitsRequired = 3;'
    '    private int hits = 0;'
    '    private int ticksElapsed = 0;'
    '    private int maxTicks = 200;'
    '    private int resultTicks = 0;'
    ''
    '    public TargetMiniGame(String gameId, int hitsRequired, int maxTicks) {'
    '        super("Targets: " + gameId, gameId);'
    '        this.hitsRequired = hitsRequired;'
    '        this.maxTicks = maxTicks;'
    '        spawnTargets();'
    '    }'
    ''
    '    private void spawnTargets() {'
    '        targets.clear();'
    '        for (int i = 0; i < TARGET_COUNT; i++) {'
    '            int x = 50 + (int)(Math.random() * 200);'
    '            int y = 50 + (int)(Math.random() * 150);'
    '            targets.add(new int[]{x, y});'
    '        }'
    '    }'
    ''
    '    @Override'
    '    protected void gameTick() {'
    '        ticksElapsed++;'
    '        if (ticksElapsed >= maxTicks && state == State.PLAYING) {'
    '            state = State.FAILURE;'
    '            MiniGameResultPacket.sendToServer(gameId, false);'
    '        }'
    ''
    '        if (state != State.PLAYING) {'
    '            resultTicks++;'
    '            if (resultTicks > 40) close();'
    '        }'
    '    }'
    ''
    '    @Override'
    '    public boolean mouseClicked(double mouseX, double mouseY, int button) {'
    '        if (state != State.PLAYING) return false;'
    ''
    '        int mx = (int) mouseX;'
    '        int my = (int) mouseY;'
    ''
    '        for (int i = targets.size() - 1; i >= 0; i--) {'
    '            int[] t = targets.get(i);'
    '            int dx = mx - t[0];'
    '            int dy = my - t[1];'
    '            if (dx * dx + dy * dy <= TARGET_RADIUS * TARGET_RADIUS) {'
    '                targets.remove(i);'
    '                hits++;'
    '                if (hits >= hitsRequired) {'
    '                    state = State.SUCCESS;'
    '                    MiniGameResultPacket.sendToServer(gameId, true);'
    '                }'
    '                return true;'
    '            }'
    '        }'
    '        return false;'
    '    }'
    ''
    '    @Override'
    '    protected void gameRender(DrawContext ctx, int mouseX, int mouseY, float delta) {'
    '        for (int[] t : targets) {'
    '            drawRing(ctx, t[0], t[1], TARGET_RADIUS, 2, 0xFFFF4444);'
    '        }'
    ''
    '        String info = "Hits: " + hits + "/" + hitsRequired'
    '            + "  Time: " + (maxTicks - ticksElapsed) / 20 + "s";'
    '        ctx.drawCenteredTextWithShadow(textRenderer, info, width / 2, 20, 0xFFFFFF);'
    ''
    '        if (state == State.SUCCESS) {'
    '            ctx.drawCenteredTextWithShadow(textRenderer, "All targets hit!", width / 2, height / 2, 0x00FF00);'
    '        } else if (state == State.FAILURE) {'
    '            ctx.drawCenteredTextWithShadow(textRenderer, "Time expired!", width / 2, height / 2, 0xFF0000);'
    '        }'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/minigame/QteMiniGame.java" -Lines @(
    'package com.example.shinobicore.modules.progression.minigame;'
    ''
    'import com.example.shinobicore.modules.progression.network.MiniGameResultPacket;'
    'import net.minecraft.client.gui.DrawContext;'
    ''
    'import java.util.ArrayList;'
    'import java.util.List;'
    ''
    'public final class QteMiniGame extends MiniGameScreen {'
    '    private static final char[] KEYS = {''A'', ''S'', ''D'', ''W'', ''Q'', ''E''};'
    '    private final List<Character> sequence = new ArrayList<>();'
    '    private int currentIndex = 0;'
    '    private int maxTicks = 150;'
    '    private int ticksElapsed = 0;'
    '    private int resultTicks = 0;'
    ''
    '    public QteMiniGame(String gameId, int sequenceLength, int maxTicks) {'
    '        super("QTE: " + gameId, gameId);'
    '        this.maxTicks = maxTicks;'
    '        for (int i = 0; i < sequenceLength; i++) {'
    '            sequence.add(KEYS[(int)(Math.random() * KEYS.length)]);'
    '        }'
    '    }'
    ''
    '    @Override'
    '    protected void gameTick() {'
    '        ticksElapsed++;'
    '        if (ticksElapsed >= maxTicks && state == State.PLAYING) {'
    '            state = State.FAILURE;'
    '            MiniGameResultPacket.sendToServer(gameId, false);'
    '        }'
    ''
    '        if (state != State.PLAYING) {'
    '            resultTicks++;'
    '            if (resultTicks > 40) close();'
    '        }'
    '    }'
    ''
    '    @Override'
    '    public boolean keyPressed(int keyCode, int scanCode, int modifiers) {'
    '        if (state != State.PLAYING) return false;'
    ''
    '        char pressed = (char) keyCode;'
    '        char expected = sequence.get(currentIndex);'
    ''
    '        if (pressed == expected) {'
    '            currentIndex++;'
    '            if (currentIndex >= sequence.size()) {'
    '                state = State.SUCCESS;'
    '                MiniGameResultPacket.sendToServer(gameId, true);'
    '            }'
    '        } else {'
    '            state = State.FAILURE;'
    '            MiniGameResultPacket.sendToServer(gameId, false);'
    '        }'
    '        return true;'
    '    }'
    ''
    '    @Override'
    '    protected void gameRender(DrawContext ctx, int mouseX, int mouseY, float delta) {'
    '        int y = height / 2;'
    '        int startX = width / 2 - (sequence.size() * 30) / 2;'
    ''
    '        for (int i = 0; i < sequence.size(); i++) {'
    '            int x = startX + i * 30;'
    '            int color;'
    '            if (i < currentIndex) color = 0xFF00FF00;'
    '            else if (i == currentIndex) color = 0xFFFFFFFF;'
    '            else color = 0xFF888888;'
    ''
    '            ctx.fill(x, y, x + 24, y + 24, 0xFF333333);'
    '            ctx.drawCenteredTextWithShadow(textRenderer,'
    '                String.valueOf(sequence.get(i)), x + 12, y + 8, color);'
    '        }'
    ''
    '        String timeLeft = "Time: " + (maxTicks - ticksElapsed) / 20 + "s";'
    '        ctx.drawCenteredTextWithShadow(textRenderer, timeLeft, width / 2, y - 30, 0xFFFFFF);'
    ''
    '        if (state == State.SUCCESS) {'
    '            ctx.drawCenteredTextWithShadow(textRenderer, "Sequence complete!", width / 2, y + 50, 0x00FF00);'
    '        } else if (state == State.FAILURE) {'
    '            ctx.drawCenteredTextWithShadow(textRenderer, "Wrong key!", width / 2, y + 50, 0xFF0000);'
    '        }'
    '    }'
    '}'
)

# ==========================================
# SECTION F: TRAINING POST BONUS
# ==========================================

Write-Utf8NoBom -Path "$baseJava/minigame/TrainingPostBonus.java" -Lines @(
    'package com.example.shinobicore.modules.progression.minigame;'
    ''
    'import com.example.shinobicore.core.log.ShinobiLogger;'
    'import com.example.shinobicore.modules.progression.config.ProgressionConfig;'
    'import net.minecraft.server.network.ServerPlayerEntity;'
    ''
    'import java.util.Map;'
    'import java.util.UUID;'
    'import java.util.concurrent.ConcurrentHashMap;'
    ''
    'public final class TrainingPostBonus {'
    '    private static final Map<UUID, Long> ACTIVE_BONUSES = new ConcurrentHashMap<>();'
    ''
    '    private TrainingPostBonus() {}'
    ''
    '    public static void applyBonus(ServerPlayerEntity player) {'
    '        long expireTick = player.getServer().getOverworld().getTime()'
    '            + ProgressionConfig.get().minigames.trainingPostDurationTicks;'
    '        ACTIVE_BONUSES.put(player.getUuid(), expireTick);'
    '        ShinobiLogger.module("progression",'
    '            player.getName().getString() + " activated training post bonus");'
    '    }'
    ''
    '    public static float getMultiplier(ServerPlayerEntity player) {'
    '        Long expireTick = ACTIVE_BONUSES.get(player.getUuid());'
    '        if (expireTick == null) return 1.0f;'
    ''
    '        long currentTick = player.getServer().getOverworld().getTime();'
    '        if (currentTick > expireTick) {'
    '            ACTIVE_BONUSES.remove(player.getUuid());'
    '            return 1.0f;'
    '        }'
    '        return ProgressionConfig.get().minigames.trainingPostMultiplier;'
    '    }'
    ''
    '    public static void cleanup(UUID playerUuid) {'
    '        ACTIVE_BONUSES.remove(playerUuid);'
    '    }'
    '}'
)

# ==========================================
# SECTION G: CLIENT KEYBINDINGS + INPUT
# ==========================================

Write-Utf8NoBom -Path "$baseJava/client/ProgressionKeyBindings.java" -Lines @(
    'package com.example.shinobicore.modules.progression.client;'
    ''
    'import net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper;'
    'import net.minecraft.client.option.KeyBinding;'
    'import net.minecraft.client.util.InputUtil;'
    'import org.lwjgl.glfw.GLFW;'
    ''
    'public final class ProgressionKeyBindings {'
    '    public static KeyBinding OPEN_PROGRESSION_KEY;'
    ''
    '    private ProgressionKeyBindings() {}'
    ''
    '    public static void register() {'
    '        OPEN_PROGRESSION_KEY = KeyBindingHelper.registerKeyBinding(new KeyBinding('
    '            "key.shinobicore.progression.open",'
    '            InputUtil.Type.KEYSYM,'
    '            GLFW.GLFW_KEY_K,'
    '            "category.shinobicore.progression"'
    '        ));'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/client/ProgressionInputHandler.java" -Lines @(
    'package com.example.shinobicore.modules.progression.client;'
    ''
    'import com.example.shinobicore.modules.progression.ui.ProgressionHubTab;'
    'import net.minecraft.client.MinecraftClient;'
    ''
    'public final class ProgressionInputHandler {'
    '    private ProgressionInputHandler() {}'
    ''
    '    public static void init() {'
    '        // Initialization if needed'
    '    }'
    ''
    '    public static void tick() {'
    '        MinecraftClient client = MinecraftClient.getInstance();'
    '        if (client.player == null) return;'
    ''
    '        if (ProgressionKeyBindings.OPEN_PROGRESSION_KEY.wasPressed()) {'
    '            client.setScreen(new ProgressionHubTab());'
    '        }'
    '    }'
    '}'
)

# ==========================================
# SECTION H: UI TABS
# ==========================================

Write-Utf8NoBom -Path "$baseJava/ui/ProgressionHubTab.java" -Lines @(
    'package com.example.shinobicore.modules.progression.ui;'
    ''
    'import com.example.shinobicore.modules.progression.client.ProgressionClientState;'
    'import net.minecraft.client.gui.DrawContext;'
    'import net.minecraft.client.gui.screen.Screen;'
    'import net.minecraft.client.gui.widget.ButtonWidget;'
    'import net.minecraft.text.Text;'
    ''
    'public final class ProgressionHubTab extends Screen {'
    '    private static final String[] TAB_NAMES = {'
    '        "Progression", "Skill Tree", "Attunement", "Stats", "Jutsu Slots", "Clan"'
    '    };'
    '    private int activeTab = 0;'
    ''
    '    public ProgressionHubTab() {'
    '        super(Text.literal("Progression"));'
    '    }'
    ''
    '    @Override'
    '    protected void init() {'
    '        super.init();'
    '        int buttonWidth = 80;'
    '        int startX = (width - TAB_NAMES.length * (buttonWidth + 5)) / 2;'
    ''
    '        for (int i = 0; i < TAB_NAMES.length; i++) {'
    '            final int tabIndex = i;'
    '            int x = startX + i * (buttonWidth + 5);'
    '            addDrawableChild(ButtonWidget.builder('
    '                Text.literal(TAB_NAMES[i]),'
    '                btn -> activeTab = tabIndex'
    '            ).position(x, 20).size(buttonWidth, 20).build());'
    '        }'
    '    }'
    ''
    '    @Override'
    '    public void render(DrawContext ctx, int mouseX, int mouseY, float delta) {'
    '        renderBackground(ctx);'
    '        super.render(ctx, mouseX, mouseY, delta);'
    ''
    '        int level = ProgressionClientState.level;'
    '        int xp = ProgressionClientState.xp;'
    '        int sp = ProgressionClientState.sp;'
    ''
    '        switch (activeTab) {'
    '            case 0 -> renderProgressionTab(ctx, level, xp, sp);'
    '            case 1 -> renderTreeTab(ctx);'
    '            case 2 -> renderAttunementTab(ctx);'
    '            case 3 -> renderStatsTab(ctx);'
    '            case 4 -> renderJutsuSlotsTab(ctx);'
    '            case 5 -> renderClanTab(ctx);'
    '        }'
    '    }'
    ''
    '    private void renderProgressionTab(DrawContext ctx, int level, int xp, int sp) {'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "Level: " + level, width / 2, 60, 0xFFFF00);'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "XP: " + xp, width / 2, 80, 0xFFFFFF);'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "SP: " + sp, width / 2, 100, 0x00FF00);'
    '    }'
    ''
    '    private void renderTreeTab(DrawContext ctx) {'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "Skill Tree (zoom/pan)", width / 2, 60, 0xFFFFFF);'
    '    }'
    ''
    '    private void renderAttunementTab(DrawContext ctx) {'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "Attunement", width / 2, 60, 0xFFFFFF);'
    '    }'
    ''
    '    private void renderStatsTab(DrawContext ctx) {'
    '        int y = 60;'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "=== Stats ===", width / 2, y, 0xFFFF00);'
    '        y += 20;'
    '        for (var entry : ProgressionClientState.statLevels.entrySet()) {'
    '            ctx.drawCenteredTextWithShadow(textRenderer,'
    '                entry.getKey() + ": " + entry.getValue(), width / 2, y, 0xFFFFFF);'
    '            y += 12;'
    '        }'
    '    }'
    ''
    '    private void renderJutsuSlotsTab(DrawContext ctx) {'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "Jutsu Slots", width / 2, 60, 0xFFFFFF);'
    '    }'
    ''
    '    private void renderClanTab(DrawContext ctx) {'
    '        ctx.drawCenteredTextWithShadow(textRenderer, "Clan Info (read-only)", width / 2, 60, 0xFFFFFF);'
    '    }'
    ''
    '    @Override'
    '    public boolean isPauseScreen() { return false; }'
    '}'
)

# ==========================================
# SECTION I: UI WIDGETS
# ==========================================

Write-Utf8NoBom -Path "$baseJava/ui/widgets/ProgressBar.java" -Lines @(
    'package com.example.shinobicore.modules.progression.ui.widgets;'
    ''
    'import net.minecraft.client.gui.DrawContext;'
    ''
    'public final class ProgressBar {'
    '    private final int x, y, width, height;'
    '    private final int bgColor, fillColor;'
    ''
    '    public ProgressBar(int x, int y, int width, int height, int bgColor, int fillColor) {'
    '        this.x = x;'
    '        this.y = y;'
    '        this.width = width;'
    '        this.height = height;'
    '        this.bgColor = bgColor;'
    '        this.fillColor = fillColor;'
    '    }'
    ''
    '    public void render(DrawContext ctx, float progress) {'
    '        ctx.fill(x, y, x + width, y + height, bgColor);'
    '        int fillWidth = (int)(width * Math.max(0, Math.min(1, progress)));'
    '        if (fillWidth > 0) {'
    '            ctx.fill(x, y, x + fillWidth, y + height, fillColor);'
    '        }'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/ui/widgets/StatRow.java" -Lines @(
    'package com.example.shinobicore.modules.progression.ui.widgets;'
    ''
    'import net.minecraft.client.gui.DrawContext;'
    'import net.minecraft.client.font.TextRenderer;'
    ''
    'public final class StatRow {'
    '    private final int x, y;'
    '    private final String label;'
    '    private final int value;'
    ''
    '    public StatRow(int x, int y, String label, int value) {'
    '        this.x = x;'
    '        this.y = y;'
    '        this.label = label;'
    '        this.value = value;'
    '    }'
    ''
    '    public void render(DrawContext ctx, TextRenderer textRenderer) {'
    '        ctx.drawTextWithShadow(textRenderer, label + ": " + value, x, y, 0xFFFFFF);'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/ui/widgets/TreeNodeWidget.java" -Lines @(
    'package com.example.shinobicore.modules.progression.ui.widgets;'
    ''
    'import net.minecraft.client.gui.DrawContext;'
    ''
    'public final class TreeNodeWidget {'
    '    private final int x, y, size;'
    '    private final String icon;'
    '    private final boolean unlocked;'
    '    private final boolean available;'
    ''
    '    public TreeNodeWidget(int x, int y, int size, String icon, boolean unlocked, boolean available) {'
    '        this.x = x;'
    '        this.y = y;'
    '        this.size = size;'
    '        this.icon = icon;'
    '        this.unlocked = unlocked;'
    '        this.available = available;'
    '    }'
    ''
    '    public void render(DrawContext ctx, net.minecraft.client.font.TextRenderer textRenderer) {'
    '        int color;'
    '        if (unlocked) color = 0xFF00FF00;'
    '        else if (available) color = 0xFFFFFF00;'
    '        else color = 0xFF555555;'
    ''
    '        ctx.fill(x, y, x + size, y + size, 0xFF222222);'
    '        ctx.fill(x + 1, y + 1, x + size - 1, y + size - 1, color);'
    '        ctx.drawCenteredTextWithShadow(textRenderer, icon, x + size / 2, y + size / 2 - 4, 0x000000);'
    '    }'
    ''
    '    public boolean isMouseOver(double mouseX, double mouseY) {'
    '        return mouseX >= x && mouseX <= x + size && mouseY >= y && mouseY <= y + size;'
    '    }'
    '}'
)

Write-Utf8NoBom -Path "$baseJava/ui/widgets/TooltipCard.java" -Lines @(
    'package com.example.shinobicore.modules.progression.ui.widgets;'
    ''
    'import net.minecraft.client.gui.DrawContext;'
    'import net.minecraft.client.font.TextRenderer;'
    ''
    'public final class TooltipCard {'
    '    private final int x, y, width, height;'
    '    private final String title;'
    '    private final String description;'
    ''
    '    public TooltipCard(int x, int y, int width, int height, String title, String description) {'
    '        this.x = x;'
    '        this.y = y;'
    '        this.width = width;'
    '        this.height = height;'
    '        this.title = title;'
    '        this.description = description;'
    '    }'
    ''
    '    public void render(DrawContext ctx, TextRenderer textRenderer) {'
    '        ctx.fill(x, y, x + width, y + height, 0xEE111111);'
    '        ctx.drawTextWithShadow(textRenderer, title, x + 5, y + 5, 0xFFFF00);'
    '        ctx.drawTextWithShadow(textRenderer, description, x + 5, y + 18, 0xCCCCCC);'
    '    }'
    '}'
)

# ==========================================
# SECTION J: MINI-GAME JSON DATA
# ==========================================

Write-Utf8NoBom -Path "$baseData/minigames/timing_basic.json" -Lines @(
    '{'
    '  "id": "timing_basic",'
    '  "type": "timing",'
    '  "params": {'
    '    "speed": 1.5,'
    '    "targetStart": 0.4,'
    '    "targetEnd": 0.6'
    '  },'
    '  "reward": {'
    '    "xp": 50,'
    '    "stat": "control"'
    '  }'
    '}'
)

Write-Utf8NoBom -Path "$baseData/minigames/target_basic.json" -Lines @(
    '{'
    '  "id": "target_basic",'
    '  "type": "target",'
    '  "params": {'
    '    "hitsRequired": 3,'
    '    "maxTicks": 200'
    '  },'
    '  "reward": {'
    '    "xp": 75,'
    '    "stat": "perception"'
    '  }'
    '}'
)

Write-Utf8NoBom -Path "$baseData/minigames/qte_basic.json" -Lines @(
    '{'
    '  "id": "qte_basic",'
    '  "type": "qte",'
    '  "params": {'
    '    "sequenceLength": 5,'
    '    "maxTicks": 150'
    '  },'
    '  "reward": {'
    '    "xp": 60,'
    '    "stat": "taijutsu"'
    '  }'
    '}'
)

Write-Utf8NoBom -Path "$baseData/minigames/pulse_circle.json" -Lines @(
    '{'
    '  "id": "pulse_circle",'
    '  "type": "pulse_circle",'
    '  "params": {'
    '    "speed": 2.0,'
    '    "targetSize": 0.5,'
    '    "tolerance": 0.1,'
    '    "duration": 10'
    '  },'
    '  "reward": {'
    '    "xp": 100,'
    '    "stat": "control",'
    '    "element": "fire"'
    '  }'
    '}'
)

# ==========================================
# SECTION K: BALANCE DATA
# ==========================================

Write-Utf8NoBom -Path "$baseData/balance/xp_curve.json" -Lines @(
    '{'
    '  "baseXp": 100,'
    '  "exponent": 1.5,'
    '  "notes": "xpForLevel(N) = baseXp * pow(N, exponent)"'
    '}'
)

Write-Utf8NoBom -Path "$baseData/balance/sp_costs.json" -Lines @(
    '{'
    '  "baseSpCostPerStat": 1,'
    '  "spCostIncrementPerLevel": 0.1,'
    '  "baseAttunementSp": 5,'
    '  "spCostIncrement": 3'
    '}'
)

Write-Utf8NoBom -Path "$baseData/balance/reputation_thresholds.json" -Lines @(
    '{'
    '  "maxReputation": 1000,'
    '  "minReputation": -1000,'
    '  "thresholds": {'
    '    "hostile": -500,'
    '    "unfriendly": -100,'
    '    "neutral": 0,'
    '    "friendly": 100,'
    '    "honored": 500,'
    '    "exalted": 1000'
    '  }'
    '}'
)

# ==========================================
# SECTION L: LANG FILE (keybinds)
# ==========================================

Write-Utf8NoBom -Path "src/main/resources/assets/shinobicore/lang/en_us.json" -Lines @(
    '{'
    '  "key.shinobicore.progression.open": "Open Progression",'
    '  "category.shinobicore.progression": "ShinobiCore Progression"'
    '}'
)

# ==========================================
# SECTION M: README
# ==========================================

Write-Utf8NoBom -Path "$baseJava/README.md" -Lines @(
    '# Progression Module'
    ''
    '## Overview'
    'Complete player progression system: Level, XP, SP, Stats, Skill Tree, Attunement, Jutsu Mastery, Reputation.'
    ''
    '## Key Behaviors'
    '- Progression NEVER resets (by design). CCA uses ALWAYS_COPY on respawn.'
    '- XP is awarded ONLY through XpSourceService (single source of truth).'
    '- All SP spends are validated server-side.'
    '- Skill tree is loaded from JSON, validated for cycles and missing prerequisites.'
    '- Attunement requires: SP cost + control stat + pulse circle mini-game success.'
    '- First element (affinity) is free. Clans may grant extra free affinities.'
    '- Combined elements (Kekkei Genkai) require base components to be unlocked first.'
    ''
    '## Commands'
    '```'
    '/shinobicore progression info'
    '/shinobicore progression statinfo'
    '/shinobicore progression addxp <amount>'
    '/shinobicore progression addsp <amount>'
    '/shinobicore progression setlevel <lvl>'
    '/shinobicore progression setstat <stat> <level>'
    '/shinobicore progression attune <element>'
    '/shinobicore progression reputation <faction> <amount>'
    '/shinobicore progression sync'
    '```'
    ''
    '## Network Packets'
    'All packets follow "read first, execute second" rule.'
    '- shinobicore:progression_action (C2S)'
    '- shinobicore:progression_attunement_attempt (C2S)'
    '- shinobicore:progression_minigame_result (C2S)'
    '- shinobicore:progression_sync (S2C)'
    '- shinobicore:progression_level_up (S2C)'
    '- shinobicore:progression_stat_changed (S2C)'
    ''
    '## Data Files'
    '- data/shinobicore/progression/tree/*.json - Skill tree nodes'
    '- data/shinobicore/progression/attunement/elements.json - Element definitions'
    '- data/shinobicore/progression/minigames/*.json - Mini-game definitions'
    '- data/shinobicore/progression/balance/*.json - Balance tuning'
    ''
    '## Config'
    'File: config/shinobicore/modules/progression.json'
    'Read once at module load. Missing fields use defaults. Invalid JSON does not crash.'
)

Write-Host ""
Write-Host "[SUCCESS] COMPLETE Progression module setup finished!" -ForegroundColor Cyan
Write-Host "[INFO] Mini-games: Timing, Target, QTE, PulseCircle" -ForegroundColor Yellow
Write-Host "[INFO] UI: ProgressionHubTab with 6 tabs + widgets" -ForegroundColor Yellow
Write-Host "[INFO] Packets: LevelUpPacket, StatChangedPacket, MiniGameResultPacket" -ForegroundColor Yellow
Write-Host "[INFO] Data: minigames JSON, balance JSON, lang file" -ForegroundColor Yellow
Write-Host "[INFO] README generated" -ForegroundColor Yellow
Write-Host ""
Write-Host "[INFO] Next: .\gradlew.bat build" -ForegroundColor Cyan