#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 11 19:50:06 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.5c.zip
