#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 09 22:39:55 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.5c.zip
